"""User - Add email_1, email_2

Revision ID: 1870f9c2051e
Revises: 7dd0f66a2cd4
Create Date: 2022-08-19 14:08:17.553252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1870f9c2051e'
down_revision = '7dd0f66a2cd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_1', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_2', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email_1'), 'users', ['email_1'], unique=True)
    op.create_index(op.f('ix_users_email_2'), 'users', ['email_2'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email_2'), table_name='users')
    op.drop_index(op.f('ix_users_email_1'), table_name='users')
    op.drop_column('users', 'email_2')
    op.drop_column('users', 'email_1')
    # ### end Alembic commands ###
