"""Article - Add price

Revision ID: 37cddbf6b1c7
Revises: 7dd0f66a2cd4
Create Date: 2022-08-19 14:12:05.905688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37cddbf6b1c7'
down_revision = '7dd0f66a2cd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('price', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'price')
    # ### end Alembic commands ###
